# Generated by Django 3.0.6 on 2020-06-01 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_way_bill_no', models.IntegerField(unique=True)),
                ('date', models.DateField(default=datetime.date(2020, 6, 1))),
                ('origin', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('shipper', models.CharField(max_length=50)),
                ('consignee', models.CharField(max_length=50)),
                ('mode', models.CharField(blank=True, max_length=50)),
                ('flight_no', models.CharField(blank=True, max_length=50)),
                ('pieces', models.IntegerField()),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('rate_per_kg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('declared_value', models.IntegerField(blank=True)),
                ('weight_charges', models.IntegerField()),
                ('other_charges', models.IntegerField(blank=True, default=0)),
                ('igst', models.IntegerField(blank=True)),
                ('cgst', models.IntegerField(blank=True)),
                ('sgst', models.IntegerField(blank=True)),
                ('total_charges', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('code', models.TextField(max_length=10, unique=True)),
                ('contract_no', models.IntegerField(unique=True)),
                ('contract_date', models.DateField(default=datetime.date(2020, 6, 1))),
                ('attendant', models.TextField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=20)),
                ('pin_code', models.IntegerField()),
                ('state', models.TextField(max_length=10)),
                ('country', models.TextField(max_length=30)),
                ('e_mail', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.IntegerField()),
                ('phone_1', models.IntegerField(blank=True)),
                ('phone_2', models.IntegerField(blank=True)),
                ('gst_no', models.TextField(max_length=30, unique=True)),
                ('gst_type', models.TextField(max_length=20)),
                ('pan_no', models.TextField(max_length=20, unique=True)),
                ('payment_type', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GenerateBill',
            fields=[
                ('generate_bill_no', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('bill', models.ManyToManyField(to='wayBill.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField(max_length=20)),
                ('destination', models.TextField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extra_charges', models.DecimalField(decimal_places=3, max_digits=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wayBill.Customer')),
            ],
        ),
    ]
