# Generated by Django 3.0.6 on 2020-06-02 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatebill',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='wayBill.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 2)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_date',
            field=models.DateField(default=datetime.date(2020, 6, 2)),
        ),
    ]
