# Generated by Django 3.0.6 on 2020-06-04 09:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0002_auto_20200602_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cgst',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 4)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='declared_value',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='igst',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sgst',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_date',
            field=models.DateField(default=datetime.date(2020, 6, 4)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatebill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wayBill.Customer'),
        ),
    ]
