# Generated by Django 3.0.6 on 2020-06-09 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0004_auto_20200605_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 9)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='igst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_date',
            field=models.DateField(default=datetime.date(2020, 6, 9)),
        ),
    ]
