# Generated by Django 3.0.6 on 2020-06-13 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0006_auto_20200612_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatebill',
            name='bill_date',
            field=models.DateField(default=datetime.date(2020, 6, 13)),
        ),
        migrations.AddField(
            model_name='generatebill',
            name='date_from',
            field=models.DateField(default=datetime.date(2020, 6, 13)),
        ),
        migrations.AddField(
            model_name='generatebill',
            name='date_to',
            field=models.DateField(default=datetime.date(2020, 6, 13)),
        ),
        migrations.AddField(
            model_name='generatebill',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='generatebill',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 13)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_date',
            field=models.DateField(default=datetime.date(2020, 6, 13)),
        ),
    ]
