# Generated by Django 3.0.6 on 2020-06-18 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0007_auto_20200613_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='sgst',
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 18)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_date',
            field=models.DateField(default=datetime.date(2020, 6, 18)),
        ),
        migrations.AlterField(
            model_name='generatebill',
            name='bill_date',
            field=models.DateField(default=datetime.date(2020, 6, 18)),
        ),
        migrations.AlterField(
            model_name='generatebill',
            name='date_from',
            field=models.DateField(default=datetime.date(2020, 6, 18)),
        ),
        migrations.AlterField(
            model_name='generatebill',
            name='date_to',
            field=models.DateField(default=datetime.date(2020, 6, 18)),
        ),
    ]
