# Generated by Django 3.0.6 on 2020-06-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0009_auto_20200618_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='rate_per_kg',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='actual_weight',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='declared_value',
        ),
    ]
