# Generated by Django 3.0.6 on 2020-06-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0010_auto_20200618_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='mode',
            field=models.CharField(max_length=50),
        ),
    ]
