# Generated by Django 3.0.6 on 2020-06-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0011_auto_20200618_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='other_charges',
            field=models.IntegerField(default=0),
        ),
    ]
