# Generated by Django 3.0.6 on 2020-07-06 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0014_auto_20200623_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 6)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='flight_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bill',
            name='mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contract_date',
            field=models.DateField(default=datetime.date(2020, 7, 6)),
        ),
        migrations.AlterField(
            model_name='generatebill',
            name='bill_date',
            field=models.DateField(default=datetime.date(2020, 7, 6)),
        ),
        migrations.AlterField(
            model_name='generatebill',
            name='date_from',
            field=models.DateField(default=datetime.date(2020, 7, 6)),
        ),
        migrations.AlterField(
            model_name='generatebill',
            name='date_to',
            field=models.DateField(default=datetime.date(2020, 7, 6)),
        ),
    ]
