# Generated by Django 3.0.6 on 2020-07-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0016_auto_20200707_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatebill',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='generatebill',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatebill',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatebill',
            name='total_other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatebill',
            name='total_weight_charges',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
