# Generated by Django 3.0.6 on 2020-07-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayBill', '0017_auto_20200707_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatebill',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='generatebill',
            name='igst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='generatebill',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
